hostname: ad
domain_base: reliyya.xyz

domain: "{{ hostname }}.{{ domain_base}}"

# ironicbadger.docker_compose_generator
appdata_path: /mnt/nfs/appdata
nfs_root: /mnt/nfs
docker_compose_generator_output_path: /home/{{ main_username }}/docker/

docker_compose_hostname: "ad"

# nfs role 
nfs_users:
  - "{{ main_username }}"

nfs_root: /mnt/nfs
nfs_appdata_source: /mnt/ssd/appdata

nfs_mounts:
  - path: "{{ appdata_path }}"
    content: true
    source: "nas.{{ domain_base }}:{{ nfs_appdata_source }}"
    fs: nfs
    opts: defaults,timeo=900,retrans=5,_netdev

