---
# generic settings
main_username: reliyya
main_groupname: "{{ main_username }}"
main_uid: "1000"
main_gid: "{{ main_uid }}"

# weareinteractive.environment
environment_config: { "PUID": "{{ main_gid }}", "PGID": "{{ main_gid }}" }

# geerlingguy.ntp
ntp_timezone: "Europe/Berlin"

# geerlingguy.security
security_ssh_port: 2222
security_ssh_password_authentication: "no"
security_ssh_permit_root_login: "no"
security_ssh_usedns: "no"
security_ssh_permit_empty_password: "no"
security_ssh_challenge_response_auth: "no"
security_ssh_gss_api_authentication: "no"
security_ssh_x11_forwarding: "no"
security_ssh_allowed_users:
  - "{{ main_username }}"
security_ssh_allowed_groups: []
security_sudoers_passwordless:
  - "{{ main_username }}"
security_autoupdate_enabled: false
security_autoupdate_blacklist: []
security_autoupdate_reboot: false
security_autoupdate_reboot_time: "03:00"
security_autoupdate_mail_to: "info@petarcubela.de"
security_autoupdate_mail_on_error: false
security_fail2ban_enabled: true
security_fail2ban_custom_configuration_template: "jail.local.j2"
docker_dir: "/home/{{ main_username }}/docker"

# geerlingguy.docker
docker_users:
  - "{{ main_username }}"
