hostname: jc-pve
domain_base: cubela.home
domain_dyndns: juro-vpn.reliyya.xyz
main_username: juro
main_uid: 1001
main_gid: 1001

# ironicbadger.docker-compose-generator
disabled_compose_files:
  - 01-traefik
docker_compose_generator_output_path: /home/{{ main_username }}/docker/
docker_compose_hostname: "jc_pve"


#storage_mp: /mnt/disk1
download_path: /mnt/disk1/downloads
nfs_root_path: /srv/nfs
ssd_storage:
  #- path: /mnt/ssd
  #  content: true
  #  diskbyid: /dev/disk/by-id/ata-Samsung_SSD_870_EVO_1TB_S75CNX0W919785R-part1
  #  fs: ext4
  #  opts: defaults

appdata_path: /home/{{ main_username }}/appdata

# ironicbadger.snapraid
snapraid_data_disks:
  - path: /mnt/disk1
    content: true
    diskbyid: /dev/disk/by-id/ata-ST4000NE001-2MA101_WJG1X7MN-part1
    fs: ext4
    opts: defaults

  #  - path: /mnt/disk2
  #    content: true
  #  - path: /mnt/disk3
  #    content: true

snapraid_parity_disks:
  - path: /mnt/parity1
    content: true
    diskbyid: /dev/disk/by-id/ata-ST4000NE001-2MA101_WJG0ZJS6-part1
    fs: ext4
    opts: defaults

snapraid_content_files:
  - /var/snapraid.content
  #- /mnt/ssd-disk1/snapraid.content

snapraid_config_excludes:
  - "*.unrecoverable"
  - /lost+found/
  - "*.!sync"
  - /tmp/

# geerlingguy.nfs
#nfs_exports:
#  ["{{ nfs_root_path }}    10.56.1.0/24(rw,sync,no_root_squash,fsid=0)"]

package_list:
  - bash-completion
  - curl
  - rsync
  - git
  - htop
  - iftop
  - iotop
  - lm-sensors
  - net-tools
  - nfs-kernel-server
  - nmap
  - openssh-server
  - python3
  - smartmontools
  - sudo
  - vim
  - tree
  - wget
  - unattended-upgrades
  - apticron
  - apt-listchanges
  - libsensors5
  - figlet
  - wakeonlan
  - ethtool
  - libpam-tmpdir
  #- apt-listbugs
  - needrestart
    #- fail2ban
 


# geerlingguy.security
security_ssh_port: 22
security_ssh_password_authentication: "yes"
security_ssh_permit_root_login: "no"
security_ssh_usedns: "no"
security_ssh_permit_empty_password: "no"
security_ssh_challenge_response_auth: "no"
security_ssh_gss_api_authentication: "no"
security_ssh_x11_forwarding: "no"
security_ssh_allowed_users:
  - "{{ main_username }}"
security_ssh_allowed_groups: []
security_sudoers_passwordless:
  - "{{ main_username }}"
security_autoupdate_enabled: true
security_autoupdate_blacklist: []
security_autoupdate_reboot: false
security_autoupdate_reboot_time: "03:00"
security_autoupdate_mail_to: "reliyya@petarcubela.de"
security_autoupdate_mail_on_error: true
security_fail2ban_enabled: true
security_fail2ban_custom_configuration_template: "jail.local.j2"
