hostname: kazcynski.reliyya.xyz

domain_base: kazcynski.reliyya.xyz

#storage_mp: /mnt/disk1
download_path: /mnt/disk1/downloads
nfs_root_path: /srv/nfs
ssd_storage:
  - path: /mnt/ssd
    content: true
    diskbyid: /dev/disk/by-id/ata-Samsung_SSD_870_EVO_1TB_S75CNX0W919785R-part1
    fs: ext4
    opts: defaults

appdata_path: /mnt/ssd/appdata

# ironicbadger.snapraid
snapraid_data_disks:
  - path: /mnt/disk1
    content: true
    diskbyid: /dev/disk/by-id/ata-WDC_WD40EFAX-68JH4N0_WD-WX52D3067UAH-part1
    fs: ext4
    opts: defaults

  #  - path: /mnt/disk2
  #    content: true
  #  - path: /mnt/disk3
  #    content: true

snapraid_parity_disks:
  - path: /mnt/parity1
    content: true
    diskbyid: /dev/disk/by-id/ata-WDC_WD40EFAX-68JH4N0_WD-WX62D302F6P3-part1
    fs: ext4
    opts: defaults

snapraid_content_files:
  - /var/snapraid.content
  #- /mnt/ssd-disk1/snapraid.content

snapraid_config_excludes:
  - "*.unrecoverable"
  - /lost+found/
  - "*.!sync"
  - /tmp/

# geerlingguy.nfs
nfs_exports:
  ["{{ nfs_root_path }}    10.56.1.0/24(rw,sync,no_root_squash,fsid=0)"]

package_list:
  - bash-completion
  - curl
  - rsync
  - git
  - htop
  - iftop
  - iotop
  - lm-sensors
  - net-tools
  - nfs-kernel-server
  - nmap
  - openssh-server
  - python3
  - smartmontools
  - sudo
  - vim
  - tree
  - wget
  - unattended-upgrades
  - apticron
  - apt-listchanges
  - libsensors5
  - figlet
  - wakeonlan
  - ethtool
  - libpam-tmpdir
  #- apt-listbugs
  - needrestart
    #- fail2ban
