main_username: reliyya
hostname: llm

domain: "{{ hostname }}.{{ domain_base}}"

# ironicbadger.docker_compose_generator
appdata_path: /mnt/nfs/appdata
media_path: /mnt/nfs/media
docker_compose_generator_output_path: /home/{{ main_username }}/docker/

docker_compose_hostname: "llm"

# nfs role
nfs_users:
  - "{{ main_username }}"

nfs_root: /mnt/nfs
nfs_appdata_source: /mnt/ssd/appdata
nfs_media_source: /mnt/disk1/media

nfs_mounts:
  - path: "{{ appdata_path }}"
    content: true
    source: "nas.{{ domain_base }}:{{ nfs_appdata_source }}"
    fs: nfs
    opts: defaults,timeo=900,retrans=5,_netdev,nofail,x-systemd.requires=network-online.target,x-systemd.automount,x-systemd.mount-timeout=90
  - path: "{{ media_path }}"
    content: true
    source: "nas.{{ domain_base }}:{{ nfs_media_source }}"
    fs: nfs
    opts: defaults,timeo=900,retrans=5,_netdev,nofail,x-systemd.requires=network-online.target,x-systemd.automount,x-systemd.mount-timeout=90


# searxng container
SEARXNG_UWSGI_WORKERS: "1"
SEARXNG_UWSGI_THREADS: "1"

package_list:
  - bash-completion
  - curl
  - rsync
  - git
  - htop
  - vim
  - nmap
  - net-tools
