hostname: media
domain_base: reliyya.xyz

domain: "{{ hostname }}.{{ domain_base}}"

# ironicbadger.docker_compose_generator
appdata_path: /mnt/nfs/appdata
media_path: /mnt/nfs/media
nfs_root: /mnt/nfs
docker_compose_generator_output_path: /home/{{ main_username }}/docker/

docker_compose_hostname: "media"

# nfs role 
nfs_users:
  - "{{ main_username }}"


gitea_runner_act_token: "very_secure"
