# main
username: reliyya
groupname: "{{ username }}"

hostname: neo
domain_base: reliyya.xyz

package_list:
  - bash
  - bash-completion
  - neovim
  - git
  - htop
  - curl
  - ca-certificates
  - xclip
  - rsync
  - net-tools
  - wakeonlan

# specific

# geerlingguy.ntp
ntp_package: chrony
