---
main_uid: "0"
main_gid: "{{ main_uid }}"
docker_compose_generator_output_path: "/root"
containers:
  - service_name: netboot
    active: true
    image: lscr.io/linuxserver/netbootxyz
    ports:
      - 3000:3000
      - 69:69/udp
      - 3001:80
    volumes:
      - ./config:/config
      - ./assets:/assets #optional
    include_global_env_vars: true
    restart: unless-stopped
