# main
#username: reliyya
#groupname: "{{ username }}"
#
#hostname: pihole
#domain_base: reliyya.xyz

package_list:
  - bash
  - vim
  - htop
  - curl
  - ca-certificates
  - xclip

# specific

dnsmasq_config_dir: /etc/dnsmasq.d
pihole_config_dir: /etc/pihole
running_as_container: false

default_domain: "reliyya.xyz"
network_cidr: 10.56.0.0/24
dhcp_range_start: 10.56.0.100
dhcp_range_end: 10.56.0.150
dhcp_router: 10.56.0.254
dhcp_active: false
#pxe_server_ip: 10.56.0.249 # lxc on neo

dns_overrides:
  # try to use sparingly and must be FQDN
  - { ip: 10.56.0.252, custom_dns: "opnsense.{{ default_domain }}" }
  - { ip: 10.56.0.252, custom_dns: "dns.{{ default_domain }}" }
  - { ip: 10.56.0.252, custom_dns: "kuma.{{ default_domain }}" }
  - { ip: 10.56.0.252, custom_dns: "ad.{{ default_domain }}" }
  - { ip: 10.56.0.252, custom_dns: "neo.{{ default_domain }}" }
  - { ip: 10.56.0.252, custom_dns: "kvm.{{ default_domain }}" }
  - { ip: 10.56.0.252, custom_dns: "ipmi.{{ default_domain }}" }
  - { ip: 10.56.1.1, custom_dns: "git.{{ default_domain }}" }
  - { ip: 100.86.250.113, custom_dns: "pearson.jc.{{ default_domain }}" }

dhcp_reservations:
  # CORE INFRASTRUCTURE
  ## FIREWALL
  - {
      mac: 90:1b:0e:57:49:b3,
      ip: 10.56.0.254,
      hostname: opnsense,
      custom_dns: ["opnsense.firewall"],
    } #
  #- { mac: ac:1f:6b:ad:dc:ab, ip: WAN, hostname: opnsense, custom_dns: ["opnsense.firewall"], } # SuperMicro igb0

  ## Network management
  - { mac: ac:1f:6b:ad:dc:aa, ip: 10.56.0.1, hostname: neo, custom_dns: [pve] } # pve node
  - { mac: bc:24:11:15:0a:63, ip: 10.56.0.2, hostname: smtp } # pct Container
  - { mac: bc:24:11:6d:8f:38, ip: 10.56.0.253, hostname: pihole } # pct Container
  - { mac: bc:24:11:09:64:c8, ip: 10.56.0.252, hostname: caddy } # pct Container
  - { mac: bc:24:11:fe:51:53, ip: 10.56.0.251, hostname: nginx } # pct Container
  - { mac: bc:24:11:55:18:58, ip: 10.56.0.250, hostname: unifi } # pct Container
  - { mac: bc:24:11:29:13:a1, ip: 10.56.0.249, hostname: pxe-netboot } # pct Container
  - { mac: bc:24:11:55:8b:ff, ip: 10.56.0.248, hostname: tailscale } # pct Container
  - { mac: bc:24:11:33:3a:a0, ip: 10.56.0.247, hostname: uptime-kuma } # pct Container
  - { mac: bc:24:11:25:f0:84, ip: 10.56.0.246, hostname: lldap } # pct Container
  #
  ## Kubernetes Cluster
  - { mac: 40:b0:34:f2:c2:9d, ip: 10.56.0.11, hostname: worker01 }
  - { mac: 40:b0:34:f3:ea:cb, ip: 10.56.0.12, hostname: node01 }
  - { mac: 40:b0:34:f8:5a:57, ip: 10.56.0.13, hostname: node02 }

  ## Network devices
  - { mac: f4:e2:c6:5c:a8:6c, ip: 10.56.0.30, hostname: usw_mini-flex }
  - { mac: f4:e2:c6:6a:fb:e8, ip: 10.56.0.31, hostname: u6 }
  - { mac: 24:2f:d0:9d:36:fb, ip: 10.56.0.40, hostname: main_switch }

  ## pain - MEDIA SERVER
  - { mac: d8:50:99:fc:2d:d0, ip: 10.56.1.1, hostname: pain } # DIY BUILD
  - { mac: d0:50:99:f6:82:29, ip: 10.56.0.20, hostname: pain-ipmi }

  ## Clients
  - { mac: 20:7B:D2:CD:07:83, ip: 10.56.2.1, hostname: void-desktop } # L380 Yoga
  - { mac: a0:d3:c1:2a:97:6e, ip: 10.56.2.2, hostname: nixos } # HP Tower
  #- { mac: tba, ip: 10.56.2.3, hostname: void-notebook } #

  ## IoT
  - { mac: 38:1a:52:29:30:5b, ip: 10.56.3.10, hostname: EPSON29305B }
