main_username: petar
ostname: scienceqorner.com
domain_base: scienceqorner.com
base_dn: "dc=scienceqorner,dc=com"

package_list:
  - bash-completion
  - curl
  - rync
  - git
  - htop
  - vim
  - nmap
  - net-tools

# ironicbadger.docker_compose_generator
appdata_path: /home/{{ main_username }}/appdata
docker_compose_generator_output_path: /home/{{ main_username }}/docker/
containers:
  # --------------- traefik ---------------------- #
  - service_name: traefik
    active: true
    image: traefik
    container_name: tr
    ports:
      - 80:80
      - 443:443
    command:
      - --log.level=info
      - --accesslog=false
      - --api.insecure=false
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls.certresolver=cloudflare
      - --certificatesresolvers.cloudflare.acme.dnschallenge=true
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - "--certificatesresolvers.cloudflare.acme.email={{ cloudflare_account_email }}"
      #- "--certificatesresolvers.cloudflare.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - --certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json
      - --serversTransport.insecureSkipVerify=true
    volumes:
      - "{{ appdata_path }}/traefik/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      #      - CF_DNS_API_TOKEN={{ scienceqorner_cloudflare_api_key }}"
      - "CLOUDFLARE_EMAIL={{ cloudflare_account_email }}"
      - "CLOUDFLARE_API_KEY={{ cloudflare_api_key }}"
    # if using .env
    restart: unless-stopped

  # --------------- ad ---------------------- #
  - service_name: lldap
    active: true
    image: lldap/lldap:stable
    container_name: lldap
    #ports:
    # For LDAP, not recommended to expose, see Usage section.
    #- "3890:3890"
    # For LDAPS (LDAP Over SSL), enable port if LLDAP_LDAPS_OPTIONS__ENABLED set true, look env below
    #- "6360:6360"
    # For the web front-end
    #- "17170:17170"
    volumes:
      - "{{ appdata_path }}/lldap_data:/data"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.lldap.rule=Host(`ad.{{ domain_base }}`)"
      - traefik.http.services.lldap.loadbalancer.server.port=17170
    environment:
      - UID={{ main_uid }}
      - GID={{ main_gid }}
      - TZ=Europe/Berlin
      - LLDAP_JWT_SECRET={{ LLDAP_JWT_SECRET }}
      - LLDAP_KEY_SEED={{ LLDAP_KEY_SEED }}
      - LLDAP_LDAP_BASE_DN={{ base_dn }}
      # If using LDAPS, set enabled true and configure cert and key path
      # - LLDAP_LDAPS_OPTIONS__ENABLED=true
      # - LLDAP_LDAPS_OPTIONS__CERT_FILE=/path/to/certfile.crt
      # - LLDAP_LDAPS_OPTIONS__KEY_FILE=/path/to/keyfile.key
      # You can also set a different database:
      # - LLDAP_DATABASE_URL=mysql://mysql-user:password@mysql-server/my-database
      # - LLDAP_DATABASE_URL=postgres://postgres-user:password@postgres-server/my-database

  # --------------- dms ---------------------- #
  - service_name: mailserver
    active: true
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    hostname: mail.scienceqorner.com
    #env_file: mailserver.env More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/latest/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25" # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "143:143" # IMAP4 (explicit TLS => STARTTLS)
      - "465:465" # ESMTP (implicit TLS)
      - "587:587" # ESMTP (explicit TLS => STARTTLS)
      - "993:993" # IMAP4 (implicit TLS)
    volumes:
      - "{{ appdata_path }}/dms/mail-data/:/var/mail/"
      - "{{ appdata_path }}/dms/mail-state/:/var/mail-state/"
      - "{{ appdata_path }}/dms/mail-logs/:/var/log/mail/"
      - "{{ appdata_path }}/dms/config/:/tmp/docker-mailserver/"
      - /etc/localtime:/etc/localtime:ro
      - "{{ appdata_path }}/dms/letsencrypt_legacy/:/etc/letsencrypt:ro"
      #- /home/petar/docker-old/swag/config/etc/letsencrypt/:/etc/letsencrypt:ro
    restart: always
    depends_on:
      - lldap
    stop_grace_period: 1m
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    environment:
      - LOG_LEVEL=debug
      - SUPERVISOR_LOGLEVEL=debug
      - ENABLE_RSPAMD=1
      - ENABLE_CLAMAV=1
      - RSPAMD_LEARN=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_QUOTAS=1
      - SPOOF_PROTECTION=1
      # >>> Postfix LDAP Integration
      - ACCOUNT_PROVISIONER=LDAP
      - LDAP_SERVER_HOST=ldap://lldap:3890
      - LDAP_SEARCH_BASE=ou=people,{{ base_dn }}
      - LDAP_BIND_DN=uid=admin,ou=people,{{ base_dn }}
      - "LDAP_BIND_PW={{ LLDAP_DMS_PASSWD }}"
      - LDAP_QUERY_FILTER_USER=(&(objectClass=inetOrgPerson)(|(uid=%u)(mail=%u)))
      - LDAP_QUERY_FILTER_GROUP=(&(objectClass=groupOfUniqueNames)(uid=%s))
      - LDAP_QUERY_FILTER_ALIAS=(&(objectClass=inetOrgPerson)(|(uid=%u)(mail=%u)))
      - LDAP_QUERY_FILTER_DOMAIN=(mail=*@%s)
      - LDAP_QUERY_FILTER_SENDERS=(|(mail=%s)(mail=admin@*))
      # <<< Postfix LDAP Integration
      # >>> Dovecot LDAP Integration
      - DOVECOT_AUTH_BIND=yes
      - DOVECOT_USER_FILTER=(&(objectClass=inetOrgPerson)(|(uid=%u)(mail=%u)))
      - DOVECOT_USER_ATTRS==uid=5000,=gid=5000,=home=/var/mail/%Ln,=mail=maildir:~/Maildir
      # <<< Dovecot LDAP Integration
      - POSTMASTER_ADDRESS=admin@{{ base_dn }}

      ## >>> SASL LDAP Authentication
      #- ENABLE_SASLAUTHD=1
      #- SASLAUTHD_MECHANISMS=ldap
      #- SASLAUTHD_LDAP_FILTER=(&(mail=%u)(objectClass=mail_user))
      ## <<< SASL LDAP Authentication

      - SSL_TYPE=letsencrypt
      - PERMIT_DOCKER=host
    cap_add:
      - SYS_PTRACE
      - NET_ADMIN # For Fail2Ban to work

  # --------------- web mail ---------------------- #
  - service_name: roundcubemail
    active: true
    image: roundcube/roundcubemail:latest
    container_name: roundcubemail
    restart: always
    volumes:
      - "{{ appdata_path }}/roundcube_data:/var/www/html"
    #ports:
    #  - "9002:80"
    environment:
      - ROUNDCUBEMAIL_DB_TYPE=sqlite
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_DEFAULT_HOST=ssl://mail.scienceqorner.com # IMAP
      - ROUNDCUBEMAIL_DEFAULT_PORT=993 # IMAP
      - ROUNDCUBEMAIL_SMTP_SERVER=ssl://mail.scienceqorner.com # SMTP
      - ROUNDCUBEMAIL_SMTP_PORT=465

    labels:
      - traefik.enable=true
      - "traefik.http.routers.roundcube.rule=Host(`mail.{{ domain_base }}`)"
      - traefik.http.services.roundcube.loadbalancer.server.port=80

  # --------------- blog ---------------------- #
  ###
  - service_name: science-blog
    active: true
    image: ghost:5-alpine
    labels:
      - traefik.enable=true
      - "traefik.http.routers.purrfectprose.rule=Host(`{{ domain_base }}`)"
      - traefik.http.routers.purrfectprose.entrypoints=websecure
      - traefik.http.routers.purrfectprose.tls.certresolver=cloudflare
    environment:
      - NODE_ENV=development
      - "url=https://{{ domain_base }}"
      #NODE_ENV: development
      - mail__from="'ScienceQorner' support@{{ domain_base }}"
      - mail__transport="SMTP"
      - mail__options__host="mail.{{ domain_base }}"
      - mail__options__port=465
      - mail__options__secure=true
      - "mail__options__auth__user=support@{{ domain_base }}"
      - "mail__options__auth__pass={{ password }}"
      - database__client=mysql
      - database__connection__host=science-blog-db
      - "database__connection__user={{ science_blog_db_user }}"
      - "database__connection__password={{ science_blog_db_pass }}"
      - database__connection__database=science-blog

    volumes:
      - "{{ appdata_path }}/science_blog/content:/var/lib/ghost/content"
    depends_on:
      - science-blog-db
    restart: unless-stopped
  - service_name: science-blog-db
    active: true
    image: mysql:8.0
    volumes:
      - "{{ appdata_path }}/science_blog/db:/var/lib/mysql"
    environment:
      - "MYSQL_ROOT_PASSWORD={{ science_blog_db_pass }}"
    restart: unless-stopped
  ###
  ### Data Services
  ###
  #  - service_name: nextcloud
  #    active: true
  #    image: nextcloud:30
  #    environment:
  #      - "NEXTCLOUD_TRUSTED_DOMAINS=nc.{{ domain_base }}"
  #      - REDIS_HOST=nextcloud-redis
  #    depends_on:
  #      - nextcloud-db
  #      - nextcloud-redis
  #    labels:
  #      - traefik.enable=true
  #      - "traefik.http.routers.nc.rule=Host(`nc.{{ domain_base }}`)"
  #    volumes:
  #      - "{{ appdata_path }}/apps/nextcloud/data:/var/www/html"
  #    restart: unless-stopped
  #  - service_name: nextcloud-db
  #    active: true
  #    image: postgres:16
  #    environment:
  #      - "POSTGRES_USER={{ nextcloud_db_user }}"
  #      - "POSTGRES_PASSWORD={{ nextcloud_db_password }}"
  #      - "POSTGRES_DB={{ nextcloud_db_name }}"
  #    volumes:
  #      - "{{ appdata_path }}/apps/nextcloud/db:/var/lib/postgresql/data"
  #    restart: unless-stopped
  #  - service_name: nextcloud-redis
  #    active: true
  #    image: redis:alpine
  #    restart: unless-stopped
  ###
  - service_name: nextcloud
    active: true
    image: lscr.io/linuxserver/nextcloud:latest
    container_name: nextcloud
    environment:
      - PUID={{ main_uid }}
      - PGID={{ main_gid }}
      - TZ=Europe/Berlin
    volumes:
      - "{{ appdata_path }}/nextcloud/config:/config"
      - "{{ appdata_path }}/nextcloud/data:/data"
    depends_on:
      - mariadb
    labels:
      - traefik.enable=true
      - "traefik.http.routers.nc.rule=Host(`nc.{{ domain_base }}`)"
    restart: unless-stopped
  - service_name: mariadb
    active: true
    image: lscr.io/linuxserver/mariadb:latest
    container_name: mariadb
    environment:
      - PUID={{ main_uid }}
      - PGID={{ main_gid }}
      - TZ=Europe/Berlin
      - MYSQL_ROOT_PASSWORD={{ NC_MYSQL_ROOT_PASSWORD }}
      - MYSQL_DATABASE={{ NC_MYSQL_DATABASE }}
      - MYSQL_USER={{ NC_MYSQL_USER }}
      - MYSQL_PASSWORD={{ NC_MYSQL_PASSWORD }}
    volumes:
      - "{{ appdata_path }}/databases/nc_db:/config"
    restart: unless-stopped
