---
###### Script to add to `docker-data/dms/config/user-patches.sh`
#---# #!/bin/bash
#---#
#---# rm -f /etc/postfix/{ldap-groups.cf,ldap-domains.cf}
#---#
#---# postconf \
#---#     "virtual_mailbox_domains = /etc/postfix/vhost" \
#---#     "virtual_alias_maps = ldap:/etc/postfix/ldap-aliases.cf texthash:/etc/postfix/virtual" \
#---#     "smtpd_sender_login_maps = ldap:/etc/postfix/ldap-users.cf"
#---#
#---# sed -i /etc/postfix/ldap-users.cf \
#---#     -e '/query_filter/d' \
#---#     -e '/result_attribute/d' \
#---#     -e '/result_format/d'
#---# cat <<EOF >> /etc/postfix/ldap-users.cf
#---# query_filter = (uid=%u)
#---# result_attribute = uid
#---# result_format = %s@example.org
#---# EOF
#---#
#---# sed -i /etc/postfix/ldap-aliases.cf \
#---#     -e '/domain/d' \
#---#     -e '/query_filter/d' \
#---#     -e '/result_attribute/d'
#---# cat <<EOF >> /etc/postfix/ldap-aliases.cf
#---# domain = example.org
#---# query_filter = (uid=%u)
#---# result_attribute = mail
#---# EOF
#---#
#---# postfix reload

main_username: root
hostname: smtp
domain_base: reliyya.xyz
base_dn: "dc=reliyya,dc=xyz"

# ironicbadger.docker_compose_generator
appdata_path: /root
docker_compose_generator_output_path: /root
containers:
  # --------------- dms ---------------------- #
  - service_name: mailserver
    active: true
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: smtp.{{ domain_base }}
    ports:
      - "25:25" # SMTP  (explicit TLS => STARTTLS, Authentication is DISABLED => use port 465/587 instead)
      - "465:465" # ESMTP (implicit TLS)
      - "587:587" # ESMTP (explicit TLS => STARTTLS)
    volumes:
      - "{{ appdata_path }}/dms/mail-logs/:/var/log/mail/"
      - "{{ appdata_path }}/dms/config/:/tmp/docker-mailserver/"
      - /etc/localtime:/etc/localtime:ro
      #- "{{ appdata_path }}/dms/letsencrypt_legacy/:/etc/letsencrypt:ro"
    restart: always
    stop_grace_period: 1m
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    environment:
      ## log
      - LOG_LEVEL=debug
      - SUPERVISOR_LOGLEVEL=debug
      ## general
      - PERMIT_DOCKER=host
      - ENABLE_POP3=0
      - ENABLE_CLAMAV=0
      - ENABLE_AMAVIS=0
      - SMTP_ONLY=1
      - ENABLE_SPAMASSASSIN=0
      - ENABLE_FETCHMAIL=0
      - POSTMASTER_ADDRESS=reliyya@petarcubela.de

      ## >>> Postfix LDAP Integration
      - ACCOUNT_PROVISIONER=LDAP
      - LDAP_START_TLS=yes
      - LDAP_SERVER_HOST=ldap://lldap.{{ domain_base }}:3890
      - LDAP_SEARCH_BASE=ou=people,{{ base_dn }}
      - LDAP_BIND_DN=uid=smtp_user,ou=people,{{ base_dn }}
      - "LDAP_BIND_PW={{ LLDAP_DMS_PASSWD }}"
      ## <<< Postfix LDAP Integration
      ## >>> SASL LDAP Authentication
      - ENABLE_SASLAUTHD=1
      - SASLAUTHD_MECHANISMS=ldap
      - SASLAUTHD_LDAP_SERVER=ldap://lldap.{{ domain_base }}:3890
      - SASLAUTHD_LDAP_START_TLS=yes
      - SASLAUTHD_LDAP_BIND_DN=uid=smtp_user,dc=reliyya,dc=xyz
      - SASLAUTHD_LDAP_PASSWORD={{ LLDAP_DMS_PASSWD }}
      - SASLAUTHD_LDAP_SEARCH_BASE=ou=people,dc=reliyya,dc=org
      - SASLAUTHD_LDAP_FILTER=(&(objectClass=inetOrgPerson)(uid=%U)(memberOf=cn=smtp_bot))
      ## <<< SASL LDAP Authentication
    cap_add:
      - SYS_PTRACE
      - NET_ADMIN # For Fail2Ban to work

