---
- name: Install Python and python3-pip
  package:
    name:
      - python3
      - python3-pip
    state:
      present

      #- name: Install docker module for Python
      #  pip:
      #    name:
      #      - docker
      #      - docker-compose
      #    state: absent

- name: Make sure that the docker folders exists
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
    state: directory
  loop:
    - "{{ docker_dir }}"

- name: Make sure that the docker folders exists
  ansible.builtin.file:
    path: "{{ item }}"
    owner: root
    group: root
    state: directory
    mode: 0710
  loop:
    - "{{ appdata_path }}/apps"
    - "{{ appdata_path }}/mediaservers"
    - "{{ appdata_path }}/arrthings"
    - "{{ download_path }}/complete"

- name: Copy the compose file
  template:
    src: templates/compose.yml
    dest: "{{ docker_dir }}/compose.yml"

- name: Copy the environment file
  template:
    src: templates/.env
    dest: "{{ docker_dir }}/.env"

    #- name: Copy the immich environment file
    #  template:
    #    src: templates/.env_immich
    #    dest: "{{ docker_dir }}/immich.env"
    #
    #- name: Copy the paperless environment file
    #  template:
    #    src: templates/.env_paperless
    #    dest: "{{ docker_dir }}/paperless.env"

- name: Copy the paperless environment file
  template:
    src: templates/docker-compose-paperless.env
    dest: "{{ docker_dir }}/docker-compose-paperless.env"

    #- name: Copy the traefik environment file
    #  template:
    #    src: templates/traefik.env
    #    dest: "{{ docker_dir }}/traefik.env"

- name: Copy the cloudflare api token
  template:
    src: templates/cf_api_token.txt
    dest: "{{ docker_dir }}/cf_api_token.txt"

- name: Make sure that the traefik data folder exists
  ansible.builtin.file:
    path: "{{ docker_dir }}/traefik-data"
    owner: "{{ main_username }}"
    group: "{{ main_username }}"
    state: directory

- name: Copy the traefik data files
  template:
    src: templates/traefik-data/traefik.yml
    dest: "{{ docker_dir }}/traefik-data/traefik.yml"
- name: Copy the traefik data files
  template:
    src: templates/traefik-data/config.yml
    dest: "{{ docker_dir }}/traefik-data/config.yml"
- name: Copy the traefik data files
  template:
    src: templates/traefik-data/acme.json
    dest: "{{ docker_dir }}/traefik-data/acme.json"

- name: Make sure that the acme file has right permissions.
  ansible.builtin.file:
    path: "{{ docker_dir }}/traefik-data/acme.json"
    owner: "{{ main_username }}"
    group: "{{ main_groupname }}"
    mode: 0600
    state: file
# ------------- NOT WORKING ------------------- #
#- name: Check for lazydocker command
#  command: command -v lazydocker >/dev/null 2>&1
#  register: installed
#  no_log: true
#  ignore_errors: true
#
#- name: Download lazydocker installer
#  get_url:
#    url: https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh
#    dest: /tmp/lazydocker-installer.sh
#    mode: "u+rwx"
#  when: installed.rc != 0
#  register: download
#
#- name: Run the install script
#  shell: /tmp/lazydocker-installer.sh
#  when: download.changed
#
#- name: Remove the lazydocker-installer.sh
#  file:
#    path: /tmp/lazydocker-installer.sh
#    state: absent
