[opnsense]
10.56.0.254

[neo]
10.56.0.1

[pihole]
10.56.0.253 ansible_user=root ansible_ssh_port=22

[caddy]
10.56.0.252 ansible_user=root ansible_ssh_port=22

[nginx]
10.56.0.251 ansible_user=root ansible_ssh_port=22

[unifi]
10.56.0.250

[netboot]
10.56.0.249 ansible_user=root ansible_ssh_port=22

[tailscale]
10.56.0.248 ansible_user=root ansible_ssh_port=22

[kuma]
10.56.0.247 ansible_user=root ansible_ssh_port=22

[lldap]
10.56.0.246 ansible_user=root ansible_ssh_port=22

[pain]
10.56.1.1

[pearson]
100.86.250.113

[neoskids:children]
pihole 
caddy 
nginx
unifi
#netboot
tailscale
kuma
lldap

[homelab:children]
pain
#pearson
neo
neoskids

[homelab:vars]
ansible_user=reliyya
ansible_port=2222
ansible_connection=ssh

[opnsense:vars]
ansible_user=reliyya
ansible_port=69

[scienceqorner]
scienceqorner.com

[petarcubela]
petarcubela.de

[vps:children]
petarcubela
scienceqorner

[vps:vars]
ansible_user=petar
ansible_port=69


#[k3s_masters]
#10.56.1.51
#10.56.1.52
#
#[k3s_nodes]
#10.56.1.50

#[k3s_cluster:children]
#k3s_masters
#k3s_nodes

