[opnsense]
10.56.0.254

[kazcynski]
10.56.1.10

[landau]
10.56.0.1

[dahmer]
10.56.1.99

[pve_cluster:children]
landau
dahmer

[k3s_masters]
10.56.1.51
10.56.1.52

[k3s_nodes]
10.56.1.50

[k3s_cluster:children]
k3s_masters
k3s_nodes

[homelab:children]
kazcynski
k3s_cluster
pve_cluster


[homelab:vars]
ansible_user=reliyya
ansible_port=2222
ansible_connection=ssh
ansible_ssh_private_key_file=~/.ssh/id_rsa

[opnsense:vars]
ansible_user=reliyya
ansible_port=69
ansible_connection=ssh
ansible_ssh_private_key_file=~/.ssh/id_rsa

[vps]
petarcubela.de
scienceqorner.com

[vps:vars]
ansible_user=petar
ansible_port=69
ansible_connection=ssh


