[opnsense]
10.56.0.254

[smtp]
10.56.0.2 ansible_user=root ansible_ssh_port=22

[dns01]
10.56.0.3 ansible_user=root ansible_ssh_port=22

[dns02]
10.56.0.4 ansible_user=root ansible_ssh_port=22

[pihole]
10.56.0.253 ansible_user=root ansible_ssh_port=22

[caddy]
10.56.0.252 ansible_user=root ansible_ssh_port=22

[unifi]
10.56.0.250

[netboot]
10.56.0.249 ansible_user=root ansible_ssh_port=22

[netbox]
#10.56.0.245 ansible_user=root ansible_ssh_port=22
#fde4:ed21:b2c0:5600:be24:11ff:fe27:476f ansible_user=root ansible_ssh_port=22
netbox.reliyya.xyz ansible_user=root ansible_ssh_port=22

[netbox_nmap_scanner]
10.56.0.244 ansible_user=root ansible_ssh_port=22
#fde4:ed21:b2c0:5600:be24:11ff:fe27:476f ansible_user=root ansible_ssh_port=22

[beszel]
#10.56.7.1 ansible_user=root ansible_ssh_port=22
#fde4:ed21:b2c0:5607:be24:11ff:fea4:6db ansible_user=root ansible_ssh_port=22
beszel.reliyya.xyz ansible_user=root ansible_ssh_port=22

[turtle] 
#10.56.1.1
#fde4:ed21:b2c0:5601::1 ansible_user=root ansible_ssh_port=22
nas.reliyya.xyz ansible_user=reliyya ansible_ssh_port=22

[qwerty]
#10.56.1.2
#fde4:ed21:b2c0:5601::2 ansible_user=root ansible_ssh_port=22
pve-qwerty.reliyya.xyz ansible_user=reliyya ansible_ssh_port=22

[llm]
#10.56.1.56 ansible_user=reliyya ansible_ssh_port=22
fde4:ed21:b2c0:5601:be24:11ff:fe19:be8d ansible_user=reliyya ansible_ssh_port=22

[caddy_srv]
10.56.1.252 ansible_user=root ansible_ssh_port=22

[caddy_dmz]
10.56.6.252 ansible_user=root ansible_ssh_port=22

[kanboard]
10.56.1.10 ansible_user=root ansible_ssh_port=22

[deb]
fde4:ed21:b2c0:5601:be24:11ff:fe39:8372 ansible_user=root ansible_ssh_port=22


[ad]
#fde4:ed21:b2c0:5601::2 ansible_user=reliyya ansible_ssh_port=22
ad.reliyya.xyz ansible_user=reliyya ansible_ssh_port=22

[media]
media.reliyya.xyz ansible_user=reliyya ansible_ssh_port=22

#[arr]
#arr.reliyya.xyz ansible_user=reliyya ansible_ssh_port=22

[jc_pve]
#192.168.178.10 ansible_user=juro ansible_ssh_port=22
juro-vpn.reliyya.xyz ansible_ssh_port=22
#100.86.250.113 ansible_ssh_port=22


[turtleskids:children]
smtp
pihole 
caddy 
unifi
netboot
dns01
dns02
netbox
beszel

caddy_srv
caddy_dmz
kanboard
ad
deb
media

[qwertyskids:children]
llm

[homelab:children]
#jc_pve
qwerty
qwertyskids
turtle 
turtleskids

[homelab:vars]
ansible_user=reliyya
ansible_port=2222
ansible_connection=ssh

[opnsense:vars]
ansible_user=reliyya
ansible_port=22

[cloud]
#cloud.com
VPS_PUBLIC_IPv4_REDACTED

[petarcubela]
petarcubela.de

[vps:children]
petarcubela
cloud

[vps:vars]
ansible_user=petar
ansible_port=69

[hetzner_pve]
pve.pinux.eu ansible_user=reliyya ansible_ssh_port=22

#[k3s_masters]
#10.56.1.51
#10.56.1.52
#
#[k3s_nodes]
#10.56.1.50

#[k3s_cluster:children]
#k3s_masters
#k3s_nodes

