---
#- hosts: pain
#  become: yes
#  vars_files:
#    - "vars/vault.yml"
#  roles:
#    - role: disks
#    - role: snapraid
#    - role: geerlingguy.docker
#    - role: ironicbadger.docker_compose_generator
#    - role: geerlingguy.security
#    - role: samba
#    - role: geerlingguy.nfs
#    #    - role: smtp # pve has mail
#
#- hosts: neo
#  become: yes
#  vars_files:
#    - "vars/vault.yml"
#  roles:
#    - role: geerlingguy.security
#    - role: geerlingguy.ntp # Proxmox docs uses chrony

- hosts: pihole
  become: yes
  vars_files:
    - "vars/vault.yml"
  roles:
    - role: dhcp-dns

#- hosts: unifi
#  become: yes
#  vars_files:
#    - "vars/vault.yml"
#  roles:
#    - role: geerlingguy.security
#    - role: geerlingguy.docker
#    - role: ironicbadger.docker_compose_generator

- hosts: caddy
  vars_files:
    - "vars/vault.yml"
  roles:
    #    - role: geerlingguy.ntp # local ntp server. delete all other
    - role: caddy
#- hosts: kuma
#  vars_files:
#    - "vars/vault.yml"
#  roles:
#    - role: geerlingguy.docker
#    - role: ironicbadger.docker_compose_generator
