---

- hosts: turtle
  become: yes
  vars_files:
    - "group_vars/secrets.yml"
  roles:
    - role: disks
    - role: snapraid
    - role: geerlingguy.security
    - role: packages
    - role: samba
      tags: filesharing
    - role: geerlingguy.nfs
      tags: filesharing
#    - role: autorestic
# ------------- NEO --------------#
- hosts: neo
  become: yes
  vars_files:
    - "group_vars/secrets.yml"
  roles:
    - role: geerlingguy.security
    - role: geerlingguy.ntp # Proxmox docs uses chrony

# ------------- NEOs KIDs --------------#
- hosts: pihole
  become: yes
  vars_files:
    - "group_vars/secrets.yml"
  roles:
    - role: dhcp-dns
#- hosts: dns01
#  become: yes
#  vars_files:
#    - "group_vars/secrets.yml"
#  roles:
#    - role: bind9
#
#- hosts: dns02
#  become: yes
#  vars_files:
#    - "group_vars/secrets.yml"
#  roles:
#    - role: bind9

- hosts: unifi
  become: yes
  vars_files:
    - "group_vars/secrets.yml"
  roles:
    - role: geerlingguy.security
    - role: geerlingguy.docker
    - role: ironicbadger.docker_compose_generator
      tags: compose

- hosts: caddy
  vars_files:
    - "group_vars/secrets.yml"
  roles:
    #    - role: geerlingguy.ntp # local ntp server. delete all other
    - role: caddy
      tags: caddy
- hosts: kuma
  vars_files:
    - "group_vars/secrets.yml"
  roles:
    - role: geerlingguy.docker
    - role: ironicbadger.docker_compose_generator
      tags: compose

- hosts: lldap
  vars_files:
    - "group_vars/secrets.yml"
  roles:
    #- role: geerlingguy.docker
    - role: ironicbadger.docker_compose_generator
      tags: compose
- hosts: netboot
  vars_files:
    - "group_vars/secrets.yml"
  roles:
    - role: geerlingguy.docker
    - role: ironicbadger.docker_compose_generator
      tags: compose

#- hosts: smtp
#  vars_files:
#    - "group_vars/secrets.yml"
#  roles:
#    #- role: geerlingguy.docker
#    - role: ironicbadger.docker_compose_generator
#      tags: compose
# ------------- cloud --------------#
- hosts: cloud
  #become: yes
  vars_files:
    - "group_vars/secrets.yml"
  roles:
    #- role: geerlingguy.docker
    - role: ironicbadger.docker_compose_generator
      tags: compose

# ------------- p.kids --------------#
- hosts: caddy_srv
  vars_files:
    - "group_vars/secrets.yml"
  roles:
    #    - role: geerlingguy.ntp # local ntp server. delete all other
    - role: caddy_srv
      tags: caddy

- hosts: caddy_dmz
  vars_files:
    - "group_vars/secrets.yml"
  roles:
    #    - role: geerlingguy.ntp # local ntp server. delete all other
    - role: caddy_dmz
      tags: caddy

#- hosts: search
#  roles:
#    #- role: geerlingguy.docker
#    - role: ironicbadger.docker_compose_generator
#      tags: compose

#- hosts: filesharing
#  vars_files:
#    - "group_vars/secrets.yml"
#  roles:
#    - role: samba 
#      tags: filesharing

- hosts: ad
  vars_files:
    - "group_vars/secrets.yml"
  roles:
    - role: geerlingguy.security
    - role: nfs-client
      tags: nfs
    - role: geerlingguy.docker
    - role: ironicbadger.docker_compose_generator
      tags: compose

- hosts: media
  vars_files:
    - "group_vars/secrets.yml"
  roles:
    - role: geerlingguy.security
    - role: nfs-client
      tags: nfs
    - role: geerlingguy.docker
    - role: ironicbadger.docker_compose_generator
      tags: compose

- hosts: arr
  vars_files:
    - "group_vars/secrets.yml"
  roles:
    - role: geerlingguy.security
    - role: nfs-client
      tags: nfs
    - role: geerlingguy.docker
    - role: ironicbadger.docker_compose_generator
      tags: compose

# ------------- qwerty.kids --------------#
- hosts: llm
  #become: yes
  #vars_files:
  #  - "group_vars/secrets.yml"
  roles:
    - role: geerlingguy.security
    - role: geerlingguy.docker
    - role: ironicbadger.docker_compose_generator
      tags: compose

# ------------ juro ------- #

- hosts: jc_pve
  become: yes
  vars_files:
    - "group_vars/secrets.yml"
  roles:
    - role: disks
    - role: snapraid
    - role: geerlingguy.docker
    - role: geerlingguy.security
      tags: sec
    - role: ironicbadger.docker_compose_generator
      tags: compose
     #-role: samba
