username: root
groupname: "{{ username }}"

shell: /bin/bash

packages:
  - htop
  - vim-full
  - usbutils
  - pciutils
  - curl
  - rsync
  - python3
  - iperf3
  - wget
  - bash
  - ca-bundle
  - ca-certificates
  - openssl-util
  - git
  - git-http
