---
- name: install samba
  apt:
    pkg: samba
    state: present
  notify: start samba service

- name: install samba config
  copy:
    src: etc/samba/smb.conf
    dest: /etc/samba/smb.conf
    owner: root
    group: root
  notify:
    - restart samba service

- name: Create group for samba users.
  group: 
    name: smbusers
    state: present 

- name: Ensure samba users are added to the samba group.
  user:
    name: "{{ item }}"
    groups: smbusers
    append: true
  with_items: "{{ smb_users }}"

- name: Add smbusers and set passwords
  shell: smbpasswd -a -s {{ item }}
  args:
    stdin: "{{ password }}\n{{ password }}"
  with_items: "{{ smb_users }}"

### nfs
#- name: Ensure nfs root exists
#  ansible.builtin.file:
#    path: "{{ item }}"
#    owner: root
#    group: root
#    state: directory
#  loop:
#    - "{{ nfs_root_path }}"
