  lldap:
    image: lldap/lldap:stable
    container_name: lldap
    ports:
      # For LDAP, not recommended to expose, see Usage section.
      - "3890:3890" ## Close this port when migrated
      # For LDAPS (LDAP Over SSL), enable port if LLDAP_LDAPS_OPTIONS__ENABLED set true, look env below
      - "6360:6360"
      # For the web front-end
      #- "17170:17170"
    networks:
      - ip6net
    volumes:
      - "{{ appdata_path }}/idm/lldap_data:/data"
      - "{{ appdata_path }}/certs/ad/letsencrypt/:/letsencrypt"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.lldap.rule=Host(`ad.{{ domain_base }}`)"
      - traefik.http.services.lldap.loadbalancer.server.port=17170
    environment:
      - "UID={{ main_uid }}"
      - "GID={{ main_gid }}"
      - TZ=Europe/Berlin
      - "LLDAP_JWT_SECRET={{ LLDAP_JWT_SECRET }}"
      - "LLDAP_KEY_SEED={{ LLDAP_KEY_SEED }}"
      - LLDAP_LDAP_BASE_DN=dc=reliyya,dc=xyz
      #If using LDAPS, set enabled true and configure cert and key path
      - LLDAP_LDAPS_OPTIONS__ENABLED=true
      - "LLDAP_LDAPS_OPTIONS__CERT_FILE=/letsencrypt/certs/ad.reliyya.xyz.crt"
      - "LLDAP_LDAPS_OPTIONS__KEY_FILE=/letsencrypt/private/ad.reliyya.xyz.key"
      # You can also set a different database:
      # - LLDAP_DATABASE_URL=mysql://mysql-user:password@mysql-server/my-database
      # - LLDAP_DATABASE_URL=postgres://postgres-user:password@postgres-server/my-database
      # If using SMTP, set the following variables
      - LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET=true
      - "LLDAP_SMTP_OPTIONS__SERVER=smtp.{{ domain_base }}"
      - LLDAP_SMTP_OPTIONS__PORT=587 # Check your smtp providor's documentation for this setting
      - LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION=STARTTLS # How the connection is encrypted, either "NONE" (no encryption, port 25), "TLS" (sometimes called SSL, port 465) or "STARTTLS" (sometimes called TLS, port 587).
      - LLDAP_SMTP_OPTIONS__USER=admin # The SMTP user, usually your email address
      - "LLDAP_SMTP_OPTIONS__PASSWORD={{ password }}" # The SMTP password
      - "LLDAP_SMTP_OPTIONS__FROM=no-reply <ad@{{ domain_base }}>" # The header field, optional: how the sender appears in the email. The first is a free-form name, followed by an email between <>.
        #- LLDAP_SMTP_OPTIONS__TO=admin <admin@reliyya.xyz> # Same for reply-to, optional.
    restart: unless-stopped


  authentik_postgresql:
    image: docker.io/library/postgres:16-alpine
    restart: unless-stopped
    container_name: authentik_postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 5s
    volumes:
      - "{{ appdata_path }}/databases/authentik_db:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_PASSWORD={{ authentik_db_pass }}"
      - "POSTGRES_USER={{ authentik_db_user }}"
      - "POSTGRES_DB={{ authentik_db_db }}"
    networks:
      - ip6net

  authentik_redis:
    image: docker.io/library/redis:alpine
    command: --save 60 1 --loglevel warning
    container_name: authentik_redis
    restart: unless-stopped
    networks:
      - ip6net
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      start_period: 20s
      interval: 30s
      retries: 5
      timeout: 3s
    volumes:
      - "{{ appdata_path }}/databases/authentik_redis:/data"
  authentik_server:
    image: ghcr.io/goauthentik/server:latest
    restart: unless-stopped
    container_name: authentik_server
    command: server
    networks:
      - ip6net
    environment:
      - "AUTHENTIK_SECRET_KEY={{ AUTHENTIK_SECRET_KEY }}"
      - "AUTHENTIK_REDIS__HOST=authentik_redis"
      - "AUTHENTIK_POSTGRESQL__HOST=authentik_db"
      - "AUTHENTIK_POSTGRESQL__USER={{ authentik_db_user }}"
      - "AUTHENTIK_POSTGRESQL__NAME={{ authentik_db_db }}"
      - "AUTHENTIK_POSTGRESQL__PASSWORD={{ authentik_db_pass }}"
      - "POSTGRES_USER={{ authentik_db_user }}"
    volumes:
      - "{{ appdata_path }}/idm/authentik_media:/media"
      - "{{ appdata_path }}/idm/authentik_custom-templates:/templates"
    ports:
      - "9000:9000"
      #- "9443:9443"
    labels:
      - traefik.enable=true
      - "traefik.http.routers.auth.rule=Host(`auth.{{ domain_base }}`)"
      - traefik.http.services.auth.loadbalancer.server.port=9443
    depends_on:
      authentik_db:
        condition: service_healthy
      authentik_redis:
        condition: service_healthy
  authentik_worker:
    image: ghcr.io/goauthentik/server:latest
    restart: unless-stopped
    container_name: authentik_worker
    command: worker
    networks:
      - ip6net
    environment:
      - "AUTHENTIK_SECRET_KEY={{ AUTHENTIK_SECRET_KEY }}"
      - "AUTHENTIK_REDIS__HOST=authentik_redis"
      - "AUTHENTIK_POSTGRESQL__HOST=authentik_db"
      - "AUTHENTIK_POSTGRESQL__USER={{ authentik_db_user }}"
      - "AUTHENTIK_POSTGRESQL__NAME={{ authentik_db_db }}"
      - "AUTHENTIK_POSTGRESQL__PASSWORD={{ authentik_db_pass }}"
      - "POSTGRES_USER={{ authentik_db_user }}"
    # `user: root` and the docker socket volume are optional.
    # See more for the docker socket integration here:
    # https://goauthentik.io/docs/outposts/integrations/docker
    # Removing `user: root` also prevents the worker from fixing the permissions
    # on the mounted folders, so when removing this make sure the folders have the correct UID/GID
    # (1000:1000 by default)
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - "{{ appdata_path }}/certs/authentik_certs:/certs"
      - "{{ appdata_path }}/idm/authentik_media:/media"
      - "{{ appdata_path }}/idm/authentik_custom-templates:/templates"
    depends_on:
      authentik_db:
        condition: service_healthy
      authentik_db:
        condition: service_healthy

