services:
  paperless_web:
    container_name: paperless
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - paperless_db
      - paperless_redis
      - paperless_gotenberg
      - paperless_tika
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paperless.rule=Host(`paperless.{{ domain_base }}`)"
      - "traefik.http.services.paperless.loadbalancer.server.port=8000"
    networks:
      - ip6net
    volumes:
      - "{{ appdata_path }}/apps/paperless_data:/usr/src/paperless/data"
      - "{{ media_path }}/documents/paperless:/usr/src/paperless/media"
      - "{{ appdata_path }}/apps/paperless_export:/usr/src/paperless/export"
      - "{{ appdata_path }}/apps/paperless_consume:/usr/src/paperless/consume"
    environment:
      - "USERMAP_UID={{ main_uid }}"
      - "USERMAP_GID={{ main_gid }}"
      - "PAPERLESS_URL=https://paperless.{{ domain_base }}"
      - USE_X_FORWARD_HOST=true
      - USE_X_FORWARD_PORT=true
      - "PAPERLESS_SECRET_KEY={{ password }}"
      - "PAPERLESS_TIME_ZONE={{ ntp_timezone }}"
      - PAPERLESS_OCR_LANGUAGE=deu
      - COMPOSE_PROJECT_NAME=paperless
      - PAPERLESS_REDIS=redis://paperless_redis:6379
      - PAPERLESS_DBHOST=paperless_db
      - PAPERLESS_TIKA_ENABLED=1
      - PAPERLESS_TIKA_GOTENBERG_ENDPOINT=http://gotenberg:3000
      - PAPERLESS_TIKA_ENDPOINT=http://tika:9998

  paperless_redis:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - "{{ appdata_path }}/databases/paperless_redis:/data"
    networks:
      - ip6net


  paperless_db:
    image: docker.io/library/postgres:16
    restart: unless-stopped
    volumes:
      - "{{ appdata_path }}/databases/paperless_pgdata:/var/lib/postgresql/data"
    environment:
      - POSTGRES_DB=paperless
      - POSTGRES_USER=paperless
      - POSTGRES_PASSWORD={{ paperless_db_passwd }}
    networks:
      - ip6net

  paperless_gotenberg:
    image: docker.io/gotenberg/gotenberg:8.7
    restart: unless-stopped
    networks:
      - ip6net
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  paperless_tika:
    image: docker.io/apache/tika:latest
    restart: unless-stopped
    networks:
      - ip6net



