services: 
  traefik:
    image: traefik
    container_name: tr
    ports:
      - 80:80
      - 443:443
    network:
      - ip6net
    command:
      - --log.level=info
      - --accesslog=false
      - --api.insecure=false
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entryPoint.to=websecure
      - --entrypoints.web.http.redirections.entryPoint.scheme=https
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls.certresolver=cloudflare
      - --certificatesresolvers.cloudflare.acme.dnschallenge=true
      - --certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare
      - --certificatesresolvers.cloudflare.acme.dnsChallenge.resolvers=[2606:4700:4700::1111]:53,[2606:4700:4700::1001]:53
      - "--certificatesresolvers.cloudflare.acme.email={{ cloudflare_account_email }}"
      #- "--certificatesresolvers.cloudflare.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - --certificatesresolvers.cloudflare.acme.storage=/letsencrypt/acme.json
      - --serversTransport.insecureSkipVerify=true
    volumes:
      - "{{ appdata_path }}/certs/ad/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - "CLOUDFLARE_EMAIL={{ cloudflare_account_email }}"
      - "CLOUDFLARE_API_KEY={{ cloudflare_api_key }}"
      #- "CLOUDFLARE_DNS_API_TOKEN={{ cloudflare_api_key }}"
    restart: unless-stopped


 networks:
   ip6net:
     enable_ipv6: true
     ipam:
       config:
         - subnet: fde4:ed21:b2c0:56f1::/64
