services:
  # AI
  ollama:
    image: ollama/ollama
    container_name: ollama
    volumes:
      - "{{ appdata_path }}/apps/ollama:/root/.ollama"
    ports:
      - 11434:11434
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - CUDA_VISIBLE_DEVICES=0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped
    runtime: nvidia
  openwebui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: openwebui
    volumes:
      - "{{ appdata_path }}/apps/open-webui:/app/backend/data"
    ports:
      - 8080:8080
    depends_on:
      - ollama
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434

      #- OAUTH_CLIENT_ID={{ ou_oauth_client_id }}
      #- OAUTH_CLIENT_SECRET={{ ou_oauth_client_secret }}
      #- OAUTH_PROVIDER_NAME=authentik
      #- OPENID_PROVIDER_URL=https://auth.reliyya.xyz/application/o/openwebui/.well-known/openid-configuration
      #- OPENID_REDIRECT_URI=https://ou.reliyya.xyz/oauth/oidc/callback
      #- ENABLE_OAUTH_SIGNUP=true
    restart: unless-stopped 
#------------ GPU monit not working with docker -------- #
#  beszel-agent:
#    image: "henrygd/beszel-agent"
#    container_name: "beszel-agent"
#    restart: unless-stopped
#    network_mode: host
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock:ro
#      # monitor other disks / partitions by mounting a folder in /extra-filesystems
#      # - /mnt/disk/.beszel:/extra-filesystems/sda1:ro
#    environment:
#      LISTEN: 45876
#      KEY: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDej/q8wFVJBEnwvRrM8B+qoAN+H+KDrmpq3PVyJTeCj"
