services:
  cloudflare-ddns:
    image: favonia/cloudflare-ddns:latest
    # Choose the appropriate tag based on your need:
    # - "latest" for the latest stable version (which could become 2.x.y
    #   in the future and break things)
    # - "1" for the latest stable version whose major version is 1
    # - "1.x.y" to pin the specific version 1.x.y
    network_mode: host
    # This bypasses network isolation and makes IPv6 easier (optional; see below)
    restart: always
    # Restart the updater after reboot
    user: "{{ main_uid }}:{{ main_gid }}"
    # Run the updater with specific user and group IDs (in that order).
    # You can change the two numbers based on your need.
    read_only: true
    # Make the container filesystem read-only (optional but recommended)
    cap_drop: [all]
    # Drop all Linux capabilities (optional but recommended)
    security_opt: [no-new-privileges:true]
    # Another protection to restrict superuser privileges (optional but recommended)
    environment:
      - CLOUDFLARE_API_TOKEN="{{ jc_pve_cf_token }}"
        # Your Cloudflare API token file
      - DOMAINS="{{ domain_dyndns }}"
        # Your domains (separated by commas)
        #- PROXIED=true
        # Tell Cloudflare to cache webpages and hide your IP (optional)

  duckdns:
    image: lscr.io/linuxserver/duckdns:latest
    container_name: duckdns
      #network_mode: host
    environment:
      - PUID="{{ main_uid }}"
      - PGID="{{ main_gid }}"
      - TZ="{{ ntp_timezone }}"
      - SUBDOMAINS=juro-vpn
      - TOKEN={{ jc_duckdns_token}}
      - LOG_FILE=true #optional
        #      - UPDATE_IP=ipv6
    volumes:
      - ./duckdns:/config #optional
        #- ./resolv.conf:/etc/resolv.conf
    restart: unless-stopped
