---
services:
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - 80:80
      - 443:443
      # - 443:443/tcp # Uncomment if you want HTTP3
      # - 443:443/udp # Uncomment if you want HTTP3
    environment:
      CF_DNS_API_TOKEN_FILE: /run/secrets/cf_api_token # note using _FILE for docker secrets
      # CF_DNS_API_TOKEN: ${CF_DNS_API_TOKEN} # if using .env
      TRAEFIK_DASHBOARD_CREDENTIALS: ${TRAEFIK_DASHBOARD_CREDENTIALS}
    secrets:
      - cf_api_token
    env_file: .env # use .env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik-data/traefik.yml:/traefik.yml:ro
      - ./traefik-data/acme.json:/acme.json
      #    - ./traefik-data/config.yml:/config.yml:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.entrypoints=http"
      - "traefik.http.routers.traefik.rule=Host(`traefik.{{ domain_base }}`)"
      - "traefik.http.middlewares.traefik-auth.basicauth.users=${TRAEFIK_DASHBOARD_CREDENTIALS}"
      - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.middlewares.sslheader.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
      - "traefik.http.routers.traefik-secure.entrypoints=https"
      - "traefik.http.routers.traefik-secure.rule=Host(`traefik.{{ domain_base }}`)"
      - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
      - "traefik.http.routers.traefik-secure.tls=true"
      - "traefik.http.routers.traefik-secure.tls.certresolver=cloudflare"
      - "traefik.http.routers.traefik-secure.tls.domains[0].main={{ domain_base }}"
      - "traefik.http.routers.traefik-secure.tls.domains[0].sans=*.{{ domain_base }}"
      - "traefik.http.routers.traefik-secure.service=api@internal"
  ### Administrative
  #swag:
  #  image: lscr.io/linuxserver/swag
  #  container_name: swag
  #  cap_add:
  #    - NET_ADMIN
  #  environment:
  #    - PUID="{{ main_uid }}"
  #    - PGID="{{ main_gid }}"
  #    - TZ="{{ ntp_timezone }}"
  #    - URL="{{ domain_base }}"
  #    - SUBDOMAINS=wildcard
  #    - VALIDATION=duckdns
  #    - DUCKDNSTOKEN=literal:REDACTED_DUCKDNS_TOKEN
  #      #- SUBDOMAINS=www
  #      #- VALIDATION=http
  #  volumes:
  #    - "{{ appdata_path }}/apps/swag:/config"
  #  ports:
  #    - 443:443
  #    - 80:80
  #  restart: unless-stopped

  librespeed:
    image: lscr.io/linuxserver/librespeed:latest
    container_name: librespeed
    environment:
      - PUID="{{ main_uid }}"
      - PGID="{{ main_gid }}"
      - TZ="{{ ntp_timezone }}"
      - PASSWORD="{{ password }}"
      - MODE=standalone
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.librespeed.rule=Host(`speed.{{ domain_base }}`)"
      - "traefik.http.routers.librespeed.entrypoints=https"
      - "traefik.http.routers.librespeed.tls=true"
      - "traefik.http.services.librespeed.loadbalancer.server.port=80"
    restart: unless-stopped

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing #optional
    environment:
      - PUID={{ main_uid }}
      - PGID={{ main_gid }}
      - TZ={{ ntp_timezone }}
    volumes:
      - "{{ appdata_path }}/apps/syncthing:/config"
      - ./syncthing_data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.syncthing.rule=Host(`sync.{{ domain_base }}`)"
      - "traefik.http.routers.syncthing.entrypoints=https"
      - "traefik.http.routers.syncthing.tls=true"
      - "traefik.http.services.syncthing.loadbalancer.server.port=8384"
    ports:
      #- 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID={{ main_uid }}
      - PGID={{ main_gid }}
      - TZ={{ ntp_timezone }}
      - JELLYFIN_PublishedServerUrl=jellfin.{{ domain_base }} #optional
      - DOCKER_MODS=linuxserver/mods:jellyfin-opencl-intel
    volumes:
      - "{{ appdata_path }}/mediaservers/jellyfin:/config"
      - /mnt/disk1/vids/movies:/media:ro
      - /mnt/disk1/vids/series:/media2:ro
    devices:
      - /dev/dri:/dev/dri
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.{{ domain_base }}`)"
      - "traefik.http.routers.jellyfin.entrypoints=https"
      - "traefik.http.routers.jellyfin.tls=true"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"
    ports:
      - 8096:8096
      #- 8920:8920 #optional
      #- 7359:7359/udp #optional
      #- 1900:1900/udp #optional
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - "{{ appdata_path }}/arrthings/data:/config"
      - /mnt/disk1/vids/movies:/movies #optional
      - "{{ download_path }}/complete/movies:/downloads" #optional
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.{{ domain_base }}`)"
      - "traefik.http.routers.radarr.entrypoints=https"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
      #    ports:
      #      - 7878:7878
    restart: unless-stopped
    #
    #  grocy:
    #    image: lscr.io/linuxserver/grocy:latest
    #    container_name: grocy
    #    environment:
    #      - PUID={{ main_uid }}
    #      - PGID={{ main_gid }}
    #      - TZ={{ ntp_timezone }}
    #    volumes:
    #      - "{{ appdata_path }}/apps/grocy:/config"
    #    ports:
    #      - 9283:80
    #    restart: unless-stopped
    #
  immich-server:
    container_name: immich_server
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    command: ["start.sh", "immich"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immich_server.rule=Host(`immich.{{ domain_base }}`)"
      - "traefik.http.routers.immich_server.entrypoints=https"
      - "traefik.http.routers.immich_server.tls=true"
      - "traefik.http.services.immich_server.loadbalancer.server.port=3001"
    ports:
      - 2283:3001
    depends_on:
      - redis
      - database
    restart: unless-stopped

  immich-microservices:
    container_name: immich_microservices
    image: ghcr.io/immich-app/immich-server:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    command: ["start.sh", "microservices"]
    volumes:
      - ${UPLOAD_LOCATION}:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env
    depends_on:
      - redis
      - database
    restart: unless-stopped

  immich-machine-learning:
    container_name: immich_machine_learning
    # For hardware acceleration, add one of -[armnn, cuda, openvino] to the image tag.
    # Example tag: ${IMMICH_VERSION:-release}-cuda
    image: ghcr.io/immich-app/immich-machine-learning:${IMMICH_VERSION:-release}
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/ml-hardware- acceleration
    #   file: hwaccel.ml.yml
    #   service: cpu # set to one of [armnn, cuda, openvino, openvino-wsl] for accelerated inference - use the `-wsl` version for WSL2 where applicable
    volumes:
      - "{{ appdata_path }}/apps/immich_model-cache:/cache"
    env_file:
      - .env
    restart: unless-stopped

  redis:
    container_name: immich_redis
    image: registry.hub.docker.com/library/redis:6.2-alpine@sha256:51d6c56749a4243096327e3fb964a48ed92254357108449cb6e23999c37773c5
    restart: unless-stopped

  database:
    container_name: immich_postgres
    image: registry.hub.docker.com/tensorchord/pgvecto-rs:pg14-v0.2.0@sha256:90724186f0a3517cf6914295b5ab410db9ce23190a2d9d0b9dd6463e3fa298f0
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    volumes:
      - "{{ appdata_path }}/apps/immich_pgdata:/var/lib/postgresql/data"
    restart: unless-stopped

  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    volumes:
      - "{{ appdata_path }}/apps/paperless_redis:/data"

  db:
    image: docker.io/library/postgres:16
    restart: unless-stopped
    volumes:
      - "{{ appdata_path }}/apps/paperless_pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless

  webserver:
    container_name: paperless
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.paperless.rule=Host(`paperless.{{ domain_base }}`)"
      - "traefik.http.routers.paperless.entrypoints=https"
      - "traefik.http.routers.paperless.tls=true"
      - "traefik.http.services.paperless.loadbalancer.server.port=8000"
    ports:
      - "8000:8000"
    volumes:
      - "{{ appdata_path }}/apps/paperless_data:/usr/src/paperless/data"
      - "{{ appdata_path }}/mediaservers/paperless:/usr/src/paperless/media"
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file:
      - docker-compose-paperless.env
      - .env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db

secrets:
  cf_api_token:
    file: ./cf_api_token.txt

networks:
  default:
    external: true
    name: proxy
