## cartman Samba Configuration

[global]
  workgroup = 
  server string = kazcynski
  security = user
  guest ok = yes
  map to guest = Bad Password

  log file = /var/log/samba/%m.log
  max log size = 50
  printcap name = /dev/null
  load printers = no

# Samba Shares
#[ISOs]
#  path = /mnt/disk1/proxmox
#  browseable = yes
#  read only = no
#  guest ok = no

[home]
  comment = petar home folder
  path = /home/reliyya
  browseable = yes
  read only = no
  guest ok = no

#[storage]
#  comment = Storage on morpheus
#  path = /mnt/storage
#  browseable = yes
#  read only = no
#  guest ok = yes

[photos]
  comment = Petar Photos
  path = /mnt/disk1/pix/upload/8cae1fe4-5f3f-4bb8-b676-24f74084a87d
  browseable = yes
  read only = no
  guest ok = yes

#[downloads]
#  comment = downloads
#  path = /mnt/disk1/downloads
#  browseable = yes
#  read only = no
#  guest ok = yes

[paperless]
  comment = Scanned Documents
  path = /home/reliyya/docker/consume
  browseable = yes 
  read only = no 
  guest ok = yes

[appdata]
  comment = appdata
  path = /mnt/disk1/appdata
  browseable = yes
  read only = no
  guest ok = yes
